### PR TITLE
Delete dead solaris build code

### PR DESCRIPTION
**Pull request by svanoort**
Solaris build is not supported, it's dead code (not even in the Makefile), and we should get rid of this. 

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
@svanoort This kind of tasks I think that it is interesting to track it in a JIRA ticket.

**Comment by recena** [comment]
@svanoort Did you remove the folder?

**Comment by recena** [comment]
:bee:

**Comment by svanoort** [comment]
@recena Yes it does remove the directory!

**Pull request merged**
