### PR TITLE
Require Java 11 in Windows Installer

### PR DESCRIPTION
**Pull request by slide**
This PR changes the behavior of the Windows installer to not continue if the selected JRE/JDK is not Java 11. See [JENKINS-67894](https://issues.jenkins.io/browse/JENKINS-67894).

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira

### CODE REVIEW

**Review by timja — APPROVED** [review]
Untested

**Review by NotMyFault — APPROVED** [review]
Looks fine, I assume Java 17 support doesn't exist here yet?

**Comment by timja** [comment]
> Looks fine, I assume Java 17 support doesn't exist here yet?

I filed https://github.com/jenkinsci/packaging/issues/323

**Comment by slide** [comment]
> Looks fine, I assume Java 17 support doesn't exist here yet?

Correct, I will put that into a separate PR after this one is merged.

**Pull request merged**
