### PR TITLE
Install tests for infra 910 core release automation

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Test Linux packaging

Checks install and service controls on:

* Debian distros oldstable, stable, and testing
* Ubuntu distros 18.04, 20.04

Checks install on:

* CentOS 7
* Fedora 33 & 34
* OpenSUSE Leap 15.3

Can't reliably test service control on CentOS, Fedora, and OpenSUSE because their systemd environments are not intended to be used inside a Docker container.  Will need to use virtual machines or something similar to test service control on those operating systems.

I'll need help from @olblak to connect this into the Jenkins job on release.ci.jenkins.io.  I couldn't tell which locations are the points of connection to insert a test into that job definition.

### CODE REVIEW

**Comment by timja** [comment]
Fastly cache purging probably needs automating for Debian repos (at least) before adding this to the packaging pipeline

**Comment by MarkEWaite** [comment]
> Fastly cache purging probably needs automating for Debian repos (at least) before adding this to the packaging pipeline

I'm not understanding how this will interact negatively with the fastly cache.  Is the concern related to the 'deb' files from the Jenkins packaging build?

I assumed that it will run inside the packaging job and read the artifacts that are packaged inside the job rather than using anything from the fastly cache.  I'll schedule some time with @olblak to get a better understanding of how to connect these tests into the existing Jenkins jobs.

**Comment by timja** [comment]
> > Fastly cache purging probably needs automating for Debian repos (at least) before adding this to the packaging pipeline
> 
> I'm not understanding how this will interact negatively with the fastly cache. Is the concern related to the 'deb' files from the Jenkins packaging build?
> 
> I assumed that it will run inside the packaging job and read the artifacts that are packaged inside the job rather than using anything from the fastly cache. I'll schedule some time with @olblak to get a better understanding of how to connect these tests into the existing Jenkins jobs.

Ah sure, I assumed that it would be pulling them from the published repos to make sure the publishing worked okay.

**Comment by MarkEWaite** [comment]
> Ah sure, I assumed that it would be pulling them from the published repos to make sure the publishing worked okay.

Good clarification. Thanks.  The ci.jenkins.io acceptance tests already have checks for installations from official sources:

* [Debian latest](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-latest-debian-package/)
* [Red Hat latest](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-latest-redhat-rpm/)
* [Debian LTS](https://ci.jenkins.io/job/Infra/job/acceptance-tests/job/install-lts-debian-package/)
* [Red Hat LTS](https://ci.jenkins.io/job/Infra/job/acceptance-tests/)

Still need acceptance test jobs for OpenSUSE and for Windows and still need Windows tests inside the packaging step.

**Comment by olblak** [comment]
It would make sense to run these tests between the packaging build stage and the packaging publish stage in order to not publish packages if something goes wrong.

The main thing to keep in mind, the packaging process is running on Kubernetes and we don't use any other docker registry than Dockerhub, so it would simplify the process to have those images ready in advance.

Personally I would :
* Build and publish testing images in advance
* Create a new PodTemplate with all images that we want to run test on, similar to [this](https://github.com/jenkins-infra/release/blob/master/PodTemplates.d/package-linux) then from the Jenkinsfile we just use this [PodTemplatel](https://github.com/jenkins-infra/release/blob/master/Jenkinsfile.d/package#L226L215)

**Comment by slide** [comment]
Do we want some sort of test for Windows?

**Comment by MarkEWaite** [comment]
> Do we want some sort of test for Windows?

Yes, we'd love to have tests for Windows, though I'm not sure this pull request is the right place for those tests.  I'm not yet sure that this pull request is worth merging.  I created it as a way to learn more about the image build process.  There are probably much better ways to test installation of the images than using this pull request.

**Comment by basil** [comment]
Superseded by recent work.

**Pull request closed without merging**
