### PR TITLE
Fix [JENKINS-31064] by bumping the java dependency to require JDK7

### PR DESCRIPTION
**Pull request by svanoort**
[[JENKINS-31064](https://issues.jenkins-ci.org/browse/JENKINS-31064)

This is b/c as of Jenkins core 1.610, class files require Java 7
Additionally, added net-tools requires entry because init script needs it
Verified using the debian:wheezy docker image for installation, Jenkins starts cleanly and handles requests.

EDITED: removing silent init script failures component, this is a separate PR

### CODE REVIEW

**Comment by svanoort** [comment]
@reviewbybees  for packaging fixes

**Comment by tfennelly** [comment]
:bee: 

Looks fine but no idea what the change really means :) So ignore this bee if you like ;)

**Comment by jtnord** [comment]
:bee:

**Comment by rsandell** [comment]
:bee:

**Comment by svanoort** [comment]
@reviewbybees done -- thanks guys!

**Comment by svanoort** [comment]
merging as pseudo-maintainer since it is tested + reviewed

**Pull request merged**
