### PR TITLE
[JENKINS-39819] shasum filename was not correct under all circumstances

### PR DESCRIPTION
**Pull request by armfergom**
See [JENKINS-39819](https://issues.jenkins-ci.org/browse/JENKINS-39819)

@reviewbybees esp. @recena

### CODE REVIEW

**Comment by recena** [comment]
🐝

**Comment by armfergom** [comment]
@rtyler Can this be merged?

**Comment by rtyler** [comment]
(shrug)

**Comment by recena** [comment]
@rtyler Thanks.

**Pull request merged**
