### PR TITLE
Rename checksum files to conventional FILENAME.sha256

### PR DESCRIPTION
**Pull request by daniel-beck**
Followup to #69 by @armfergom, renaming the checksum file.

CC @svanoort

### CODE REVIEW

**Comment by svanoort** [comment]
:+1:

**Comment by recena** [comment]
👍 For the renaming but I prefer the idea here https://github.com/jenkinsci/packaging/pull/70, it should be reviewed though. Only one checksum file per folder.

**Comment by armfergom** [comment]
👍 for the renaming, although I think this PR si no longer applicable since #69 was reverted. I'd like to create another PR to replace #69 and will take into account this naming proposal. Thanks @daniel-beck !

**Comment by daniel-beck** [comment]
Superseded by #75

**Pull request closed without merging**
