### PR TITLE
[FIXED JENKINS-30280] remove dotnet installer dependency.

### PR DESCRIPTION
**Pull request by jtnord**
DotNet 2.0 is included in the OS or all modern systems, so don't add the
assembly - which removes the requirement for dotnet 2.0.

[JENKINS-30280](https://issues.jenkins-ci.org/browse/JENKINS-30280)

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
@jtnord It seems there is a conflict.

**Comment by jtnord** [comment]
@recena #23 was just merged. fix is the same and a rebase force push will be coming your way.

**Comment by recena** [comment]
:bee:

**Comment by recena** [comment]
@jtnord If you need a tester, ping me.

**Comment by jtnord** [comment]
@recena noticed an issue whilst rebasing so fix is slightly different

**Comment by recena** [comment]
@jtnord Better :+1:

**Comment by svanoort** [comment]
I'm not particularly familiar with MSI packaging, so let me make sure I understand correctly:

* msbuild is being run with bootstrapper.xml to generate a setup.exe for systems without dotnet 2.0 preinstalled
* This is no longer necessary, so the setup.exe does not need to be created or packaged

**Three questions:**
* Is there a reason for [build-on-jenkins.sh](https://github.com/jenkinsci/packaging/blob/57a18a5cdd24f107eed66a8c932c48944c21507d/msi/build-on-jenkins.sh) to still work with the bootstrapper.xml ? 
* Can we remove the bootstrapper.xml completely?
* Longer-term: Would it make sense to stop distributing a ZIP and instead just supply the MSI file (since all components should already be compressed)?

**Comment by jtnord** [comment]
> * Is there a reason for build-on-jenkins.sh to still work with the bootstrapper.xml ?

missed it :-)

> * Can we remove the bootstrapper.xml completely?

yes

> Longer-term: Would it make sense to stop distributing a ZIP and instead just supply the MSI file (since all components should already be compressed)?

Potentially - I know some people like the zips as you see that it is obviously corrupted and/or some corporate proxies block msi/exes (most of those that do will also open the zip and inspect it so...)

I would probably just say yes here.

**Comment by svanoort** [comment]
> Potentially - I know some people like the zips as you see that it is obviously corrupted and/or some corporate proxies block msi/exes (most of those that do will also open the zip and inspect it so...)

True on both points.   I have to wonder also if anyone is doing scripted installs on windows (using the setup.exe)?  Honest question, since I have no idea what is common for our windows Jenkins users.

**Comment by jtnord** [comment]
> * msbuild is being run with bootstrapper.xml to generate a setup.exe for systems without dotnet 2.0 preinstalled

It creates a setup that installs .net 2.0 and then kicks the jenkins installer.

> * This is no longer necessary, so the setup.exe does not need to be created or packaged

correct

**Comment by jtnord** [comment]
> *  I have to wonder also if anyone is doing scripted installs on windows

Should be using `msiexec` and the `msi` for that.

**Comment by svanoort** [comment]
> Should be using msiexec and the msi for that.

True...  alright :bee: with a tiny risk of breaking people if they're doing something wacky with the setup.exe (at which point they would be be nudged towards direct consumption of the MSI anyway).

**Comment by jtnord** [comment]
@reviewbybees done

**Comment by svanoort** [comment]
Per discussion today, this is being held back a little bit and then rolled out to get baked in before the next LTS, for safety.

**Pull request merged**
