### PR TITLE
[Typo] s/allways/always

### PR DESCRIPTION
**Pull request by juneeighteen**
* Fix typo in deb/build/debian/jenkins.init

### CODE REVIEW

**Comment by juneeighteen** [comment]
@jglick , Do I need to open anything in the Jenkins Jira system to address a quick typo?

**Comment by jglick** [comment]
No, that sounds like overkill

**Comment by timja** [comment]
This branch is obsolete, hopefully from ~next week https://github.com/jenkinsci/packaging/tree/INFRA-910-core-release-automation will be merged to master.

It doesn't have that file at least by the same name.

**Comment by MarkEWaite** [comment]
@timja I checked the installation of the weekly that is on my Debian machine and that spelling error is still in the packaging in `/etc/init.d/jenkins`.  Since we've been building weekly with core release automation for several weeks, I assumed that the weekly build would already show the results of the work on the INFRA-910 branch.  Did I misunderstand something there?

**Comment by timja** [comment]
Hmm, it is there, but file finder doesn't find it for some reason

https://github.com/jenkinsci/packaging/find/INFRA-910-core-release-automation

**Pull request merged**
