### PR TITLE
fix:Change to use 127.0.0.1 instead of localhost in browser launch at end of install 

### PR DESCRIPTION
**Pull request by slide**
Change to use 127.0.0.1 instead of localhost, this fixes https://issues.jenkins.io/browse/JENKINS-41101

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by daniel-beck** [comment]
Isn't there a dependency on IPv4 for 127.0.0.1? Is that always present on Windows?

I think we implemented the opposite change somewhere else not too long ago.

**Comment by slide** [comment]
> Isn't there a dependency on IPv4 for 127.0.0.1? Is that always present on Windows?

No, IPv4 is not always present (it can be disabled)

> 
> I think we implemented the opposite change somewhere else not too long ago.

Do you remember where this was? I'd like to look at the discussion if possible.

**Comment by daniel-beck** [comment]
https://github.com/jenkinsci/maven-hpi-plugin/pull/169 might be what I thought was the change "not too long ago" (yay memory), but I cannot find what motivated that position specifically.

https://github.com/jenkinsci/jenkins-test-harness/pull/9 was before, but I probably just checked this for consistency/completeness – but FWIW another point for the `localhost` in acrive use, even though all of these are in non-production environments.

I mean, if I'm wrong here it wouldn't be the first time 😄 What is this change supposed to accomplish? I read the ticket but don't understand it.

**Comment by slide** [comment]
Honestly, now that I look at the issue again, I think its bogus. Sorry for the cruft.

**Pull request closed without merging**
