### PR TITLE
Proposed fix for JENKINS-64212

### PR DESCRIPTION
**Pull request by tam116**
Change the regex to detect just the major version of java

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
I've confirmed that the new check works with all the Linux JDK 8 and JDK 11 versions that I have available.  That includes:

* jdk-11.0.2
* jdk-11.0.3+7
* jdk-11.0.4+11
* jdk-11.0.5+10
* jdk-11.0.6+10
* jdk-11.0.7+10
* jdk-11.0.8+10
* jdk-11.0.8+10-openj9
* jdk-11.0.9+11
* jdk-11.0.9+11-openj9
* jdk-11.0.9.1
* jdk8u212-b03
* jdk8u222-b10
* jdk8u232-b09
* jdk8u242-b08
* jdk8u252-b09
* jdk8u262-b10
* jdk8u262-b10-openj9
* jdk8u265-b01
* jdk8u265-b01-openj9
* jdk8u272-b10
* jdk8u272-b10-openj9
* jdk8u275-b01


It failed as expected for:

* jdk-12
* jdk-12.0.1+12
* jdk-12.0.2+10

The sed pattern seems to be specific t GNU sed.  It does not match on OpenBSD or FreeBSD.  I suspect it will not match on macOS.  Since this is inside a Debian Docker image, it is safe to assume that GNU sed will be used.

**Review by slide — APPROVED** [review]

**Comment by jackdpeterson** [comment]
I can confirm that manually applying this change for Jenkins 2.249.3 w/ OpenJDK 11.0.9.1 on Ubuntu 20.04 allow the Jenkins service to come up as expected.

**Comment by dc232** [comment]
Hi, can I confirm that this PR also works for 
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)

I am receiving the following error

```
Found an incorrect Java version
Java version found:
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
Aborting
systemd[1]: jenkins.service: Control process exited, code=exited, status=1/FAILURE
```

**Comment by dc232** [comment]
right did some further digging, turns out that the above is supported by Jenkins however  after running the following commands
```
sudo apt install openjdk-11-jre-headless
sudo apt install jenkins
```
after adding the apt-key and updating

the file downloaded is original unpatched file
when I added the changes presented in the commit to 
```
/etc/init.d/jenkins
```

and then run the commands 

```
systemctl daemon-reload
systemctl restart jenkins
```

did the system then start correctly i.e
```
jenkins.service - LSB: Start Jenkins at boot time
     Loaded: loaded (/etc/init.d/jenkins; generated)
     Active: active (running) since Fri 2020-11-20 19:59:04 UTC; 21s ago
       Docs: man:systemd-sysv-generator(8)
      Tasks: 50 (limit: 19660)
     Memory: 2.5G
     CGroup: /system.slice/jenkins.service
             ├─20258 /usr/bin/daemon --name=jenkins --inherit --env=JENKINS_HOME=/var/lib/jenkins --output=/var/log/jenkins/jenkins.log --pidfile=/var/run/jenkins/jenkins.pid -- /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
             └─20260 /usr/bin/java -Djava.awt.headless=true -jar /usr/share/jenkins/jenkins.war --webroot=/var/cache/jenkins/war --httpPort=8080
```
can this commit please be merged into the master branch that deals with the package downloaded via 

```sudo apt install jenkins
```

**Comment by ValorHeart** [comment]
Hello, Confirmed that changing manually /etc/init.d/jenkins allows Jenkins to start once again with Java 11.
2.249.3, OpenJDK 11.0.9.1 on Ubuntu 20.04

**Comment by MarkEWaite** [comment]
@dc232 wrote:

> can this commit please be merged into the master branch that deals with the package downloaded via

It was merged into the master branch a week before your comment requested that it be merged.

The change is not visible in your installation because a new Jenkins version has not been delivered that includes the fix.  Your options include:

* Apply the fix to your local copy of /etc/init.d/jenkins
* Apply a different fix of your choosing to your local copy (disable the check for Java version, use a different check, etc.)
* Stay with Java 11.0.8 on Ubuntu 20.04 until a new Jenkins release is available that includes the fix

**Comment by MarkEWaite** [comment]
This fix resolves the issue listed in Cameron McKenzie's post at https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/jenkins-ubuntu-20-install-git-jdk-java-ci-cd .  Cameron's technique is also valid, run with JDK 8 rather than JDK 11.  With this fix and Jenkins 2.263.1, JDK 11 on Ubuntu 20.04 is expected to run just fine.

**Comment by mkeckeis** [comment]
Hi - I would like to incorporate this change so that I can resolve this issue:

https://askubuntu.com/questions/1139046/jenkins-error-incorrect-java-version-for-java11-after-removing-java11-and-ins

I dont think the change is in the installable version yet. Any idea how I can do that?

**Comment by MarkEWaite** [comment]
@mkeckeis you can modify your installed copy of `/etc/init.d/jenkins` and place the change that is listed in https://github.com/jenkinsci/packaging/pull/198/files in that file.

You can't make the change in the installable version because that would require a new version of the installable version.  It would require a release Jenkins 2.249.4 to supersede Jenkins 2.249.3.  A new release will be delivered on Wednesday, Jenkins 2.263.1.  Jenkins 2.263.1 will include the fix.

The fix has been applied to Jenkins weekly releases and is already being delivered in Jenkins weekly releases.

**Pull request merged**
