### PR TITLE
Try signing the installer in the release flow

### PR DESCRIPTION
**Pull request by slide**

### CODE REVIEW

**Comment by slide** [comment]
@olblak Is this easy to try in the release setup?

**Comment by olblak** [comment]
This Jenkinsfile needs to be updated first https://github.com/jenkins-infra/release/blob/91726b3d0686fbe3c60997120af7e0a82f5517f4/Jenkinsfile.d/package#L55 in order to use the jenkinsci/packaging instead of my fork, and the correct git branch, then you can merge. Feel free to open a PR

**Comment by slide** [comment]
With the PR merged for the update of the branch, is this being run anywhere now?

**Comment by olblak** [comment]
I don't have merge permission on this repository (jenkinsci/packaging) :) but as soon as this PR lands on 'INFRA-910-core-release-automation', it will be used by the release environment.

**Comment by oleg-nenashev** [comment]
Just ping me. I did not know you had no permissions

**Pull request merged**
