### PR TITLE
Revert "[JENKINS-38134] Generate shasum for war, windows and osx inst…

### PR DESCRIPTION
**Pull request by daniel-beck**
…allers"

This reverts commit 916f556aad4d6fbbc7c8044c3056005cb29f652f.

Reverts #69 since [it seems to accidentally change the directory structure](https://github.com/jenkinsci/packaging/pull/69#discussion_r81468558).

### CODE REVIEW

**Comment by daniel-beck** [comment]
CC @armfergom FYI

**Comment by oleg-nenashev** [comment]
👍 as a hotfix

**Comment by daniel-beck** [comment]
I don't know when exactly @kohsuke returns to create the new weekly and LTS release, but I believe #69 would impact directory structure, so I'll just merge this now to be safe (in the hopes it doesn't break anything else).

**Comment by armfergom** [comment]
@daniel-beck fair enough, thanks for this. I'l think of a different proposal now that I know more. Sorry for the trouble.

**Pull request merged**
