### PR TITLE
[JENKINS-48099] Fix repo file for LTS releases

### PR DESCRIPTION
**Pull request by daniel-beck**
https://issues.jenkins-ci.org/browse/JENKINS-48099

100% untested, just based on advice in the issue description.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@jenkinsci/code-reviewers

**Comment by MarkEWaite** [comment]
I recommend against this change until we have a way to duplicate the problem.  I was [unable to duplicate it](https://issues.jenkins-ci.org/browse/JENKINS-48099?focusedCommentId=320185&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-320185).

**Comment by oleg-nenashev** [comment]
@daniel-beck @MarkEWaite what would be our next steps here? Just close since we cannot reproduce it?

**Comment by MarkEWaite** [comment]
Close it since we cannot reproduce it.

**Pull request closed without merging**
