### PR TITLE
[JENKINS-30764] if running on cygwin translate the temp path.

### PR DESCRIPTION
**Pull request by jtnord**
Fixes [JENKINS-30764](https://issues.jenkins-ci.org/browse/JENKINS-30764)

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
:bee:

**Comment by varmenise** [comment]
:bee:

**Comment by jtnord** [comment]
@reviewbybees done

**Comment by jtnord** [comment]
merging as a sort of maintainer.

**Comment by svanoort** [comment]
:+1: belatedly

**Pull request merged**
