### PR TITLE
Add script & helper for packaging docker image to handle running under different users

### PR DESCRIPTION
**Pull request by svanoort**
Attempts to create users & groups on the fly so you can use a volume mount without breaking permissions

### CODE REVIEW

**Comment by svanoort** [comment]
@reviewbybees

**Comment by olivergondza** [comment]
To my understanding this require to invoke `docker run` with special arguments in order to get the account created and you have to provide ids from the outside. How can this be used from `docker.inside { ... }` step?

**Comment by svanoort** [comment]
@olivergondza More or less the size of it -- in cases like this we can't really do 'inside' if we need to sudo in container.   It needs container-side configuration -- which this lands on the fly. 

If you always run under the same user you can use this as a base image and then prebake that into a custom image, but this approach lets you run under whatever user you like with sudo-ability in container.

**Comment by svanoort** [comment]
Merging since this one is uncontroversial at this point (no objections, and one solid approval).

**Pull request merged**
